# Generated by Django 5.2.15 on 2026-06-19 11:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("inventory", "0002_alter_supplier_inn_alter_supplier_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Количество")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_items",
                        to="inventory.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар в продаже",
                "verbose_name_plural": "Товары в продаже",
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "buyer_name",
                    models.CharField(max_length=255, verbose_name="Покупатель"),
                ),
                (
                    "sale_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Дата продажи",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="companies.company",
                        verbose_name="Компания",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        related_name="sales",
                        through="sales.ProductSale",
                        to="inventory.product",
                        verbose_name="Товары",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продажа",
                "verbose_name_plural": "Продажи",
            },
        ),
        migrations.AddField(
            model_name="productsale",
            name="sale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="sales.sale",
                verbose_name="Продажа",
            ),
        ),
    ]
